# place all worker configuration variables here

name: huggingface-walkthrough
network: allora-testnet-1
faucet_url: https://faucet.testnet-1.testnet.allora.network/
node_public_ip: ""
worker:
  allora_heads: /dns/head-0-p2p.testnet-1.testnet.allora.network/tcp/32130/p2p/12D3KooWLBhsSucVVcyVCaM9pvK8E7tWBM9L19s7XQHqqejyqgEC,/dns/head-1-p2p.testnet-1.testnet.allora.network/tcp/32131/p2p/12D3KooWEUNWg7YHeeCtH88ju63RBfY5hbdv9hpv84ffEZpbJszt,/dns/head-2-p2p.testnet-1.testnet.allora.network/tcp/32132/p2p/12D3KooWATfUSo95wtZseHbogpckuFeSvpL4yks6XtvrjVHcCCXk

  allora_rpc_address: https://allora-rpc.testnet-1.testnet.allora.network/
  allora_api_address: https://allora-api.testnet-1.testnet.allora.network/
  topic_id: 4
  mnemonic: ""
  hex_coded_pk: ""
  address: ""